### ISSUE TITLE
More generic example/volwjt & Arch Linux AUR

### ISSUE THREAD

**Issue by Nycroth** [ianremmler/wjt#2]
Love this! Thanks for posting about it on the Suckless mailing list.

I modified the volume example to work on both my Laptop (2 different sound cards) and Desktop. Just wanted to pass it back in case you wanted to merge it.

I also created an [Arch Linux AUR](https://aur.archlinux.org/packages/wjt/) package. If you ever want to take over maintainership, you're welcome to. If not, I'll just check your GitHub repo's tags every now and then for changes.

```diff
diff --git a/examples/volwjt b/wjt-vol
index 52e7851..528636b 100755
--- a/examples/volwjt
+++ b/wjt-vol
@@ -2,15 +2,24 @@

 # adjust volume using wjt and amixer

-initvol="$(amixer get Master | tr -d '[]%' | awk '/Left: Playback/ { print $5 }')"
+main_ctrl="$(amixer scontrols |
+       sed -n "s/^Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
+       head -n 1)"
+
+initvol="$(amixer get "$main_ctrl" | tr -d '[]%' |
+       awk '
+               /Mono: Playback/ { print $4 }
+               /Left: Playback/ { print $5 }
+       ')"
+

 wjt -p "volume:" -z m -x "$initvol" "$@" | while read vol; do
        case "$vol" in
                m)
-                       amixer -q set Master toggle
+                       amixer -q set "$main_ctrl" toggle
                        ;;
                *)
-                       amixer -q set Master "$vol%"
+                       amixer -q set "$main_ctrl" "$vol%"
                        ;;
        esac
 done
```

**Comment by ianremmler** [comment]
Thanks for making the AUR package and the modified volume script.  I don't use Arch, so the package is all yours!  I'll keep the volume script as is in the repo since it's a nice, simple usage example, but feel free to point people at this issue for the advanced amixer mungery edition.
