### ISSUE TITLE
Step from nonzero to zero isn't registered.

### ISSUE THREAD

**Issue by tdukv** [ianremmler/wjt#4]
When the first step/jump is from nonzero to zero nothing gets output.

**Comment by ianremmler** [comment]
Good catch! I think the fix should really be to set `valout = initval` before the `adjustval(initval)` call in `setup()`, though, since `initval` can be initialized to something other than 0 in `config.h`. You can update the PR if you'd like or I can just fix it; just let me know.

Thanks!

**Comment by tdukv** [comment]
Sure, you can just fix it, the PR is there just because the repo looked inactive and someone else might have wanted to pick it up.

**Comment by ianremmler** [comment]
Fixed in 931b8f9.
